<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selamat datang di Facebook, AeruUnggah _db3783</name>
   <tag></tag>
   <elementGuidId>ef96fa11-1db2-4d99-bc40-c9b9ed4d78d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_Ua']/div/div/div/div[3]/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bdao358l.om3e55n1.g4tp4svg.alzwoclg.cgu29s5g.i15ihif8.aeinzg81.jcxyg2ei.o9w3sbdw.sr926ui1.jl2a5g8c.bdjfgm2q.dhod7fyx.ir39z7dx.gqe1mzv8.av1hlb45</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c5351d8-8ff4-4114-9f45-23ae84d93d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>37b0ccef-1302-4a6d-93e0-aabf07fb1e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bdao358l om3e55n1 g4tp4svg alzwoclg cgu29s5g i15ihif8 aeinzg81 jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c bdjfgm2q dhod7fyx ir39z7dx gqe1mzv8 av1hlb45</value>
      <webElementGuid>cc72f266-9e3f-431c-b4fb-835cf8795194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selamat datang di Facebook, AeruUnggah Foto ProfilTambahkan foto agar teman dapat mengenali Anda dengan mudah.Tambahkan FotoCari Orang yang Anda KenalCari berdasarkan nama atau cari teman sekolah dan rekan kerjaMengenal pengaturan privasiAnda mengendalikan cara Anda membagikan sesuatu dengan orang dan aplikasi di Facebook.Ikuti Tur Privasi</value>
      <webElementGuid>46f926dc-d0e1-438a-a052-b956b16a1ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_Ua&quot;)/div[1]/div[1]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg&quot;]/div[@class=&quot;g4tp4svg om3e55n1 cqf1kptm alzwoclg&quot;]/div[@class=&quot;alzwoclg cqf1kptm om3e55n1&quot;]/div[@class=&quot;alzwoclg cqf1kptm om3e55n1 kyj84mfa cofpoq2j&quot;]/div[@class=&quot;alzwoclg cqf1kptm p1t2w4gn fawcizw8 om3e55n1 g4tp4svg&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg jez8cy9q jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c fawcizw8 h93itd9g&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg jg3vgc78 cgu29s5g i15ihif8 aeinzg81 sl27f92c hael596l sr926ui1 jl2a5g8c kwmpab9d fawcizw8 red7f7t1&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg cgu29s5g i15ihif8 aeinzg81 jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c bdjfgm2q dhod7fyx ir39z7dx gqe1mzv8 av1hlb45&quot;]</value>
      <webElementGuid>8922757e-8832-4582-b741-389e5ed3bd39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_Ua']/div/div/div/div[3]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>901a04f7-c6a8-42d6-bb4b-e13aa585d91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::div[1]</value>
      <webElementGuid>83913007-d7df-49cd-8c04-a67bab7b3f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/following::div[4]</value>
      <webElementGuid>4906f08c-3e1b-48d0-90e2-f6ff7bde40b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>8f9e653a-c434-4a18-b418-94ac27833fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selamat datang di Facebook, AeruUnggah Foto ProfilTambahkan foto agar teman dapat mengenali Anda dengan mudah.Tambahkan FotoCari Orang yang Anda KenalCari berdasarkan nama atau cari teman sekolah dan rekan kerjaMengenal pengaturan privasiAnda mengendalikan cara Anda membagikan sesuatu dengan orang dan aplikasi di Facebook.Ikuti Tur Privasi' or . = 'Selamat datang di Facebook, AeruUnggah Foto ProfilTambahkan foto agar teman dapat mengenali Anda dengan mudah.Tambahkan FotoCari Orang yang Anda KenalCari berdasarkan nama atau cari teman sekolah dan rekan kerjaMengenal pengaturan privasiAnda mengendalikan cara Anda membagikan sesuatu dengan orang dan aplikasi di Facebook.Ikuti Tur Privasi')]</value>
      <webElementGuid>c913e898-2633-45f7-b5e0-fbc6175e25ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
