<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>3ee670a4-ec1f-4eaa-9fa3-bada0ce98484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='reset_action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;reset_action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfd4236d-3ab4-4775-9eda-59a14aa29542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ba137bb9-d58b-4d97-84af-3ea33333e963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy</value>
      <webElementGuid>ba4416f0-9d4d-4f6a-9fa3-49afe6580191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reset_action</value>
      <webElementGuid>f28d5777-cc8a-46b2-af7f-ff4eb8b5618a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>106dab3b-8b6e-4b22-9bad-5d707b25c3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>6d48845e-a66c-4410-a0fe-f3279505a428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2_QT&quot;)/div[@class=&quot;mvl ptm uiInterstitial _9np_ uiInterstitialLarge uiBoxWhite&quot;]/div[@class=&quot;uiInterstitialBar uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;rfloat _ohf&quot;]/button[@class=&quot;_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy&quot;]</value>
      <webElementGuid>18a4ae5c-e35b-4f29-afb2-04a3381a6dd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='reset_action']</value>
      <webElementGuid>35ac0cf2-b033-4a52-a79b-178925a0ef3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_QT']/div/div[3]/div/div/button</value>
      <webElementGuid>6513928e-558d-4ba3-992f-8b6ee67f5b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>ee8b0cfb-0423-4c63-af7a-773be10b46dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fchaerin.c196@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>2fffbc3f-372a-4e6d-a36a-ccfbf4b46154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Didn', &quot;'&quot;, 't get a code?')])[1]/preceding::button[1]</value>
      <webElementGuid>7cfde2cb-8292-4003-a95f-cdd9ba554933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::button[1]</value>
      <webElementGuid>0cbe444d-a336-4e39-98ec-877524a3606b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>7d2145e5-131c-4959-bc12-74c7745d7f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>66081fbc-9c0a-4ad8-a2f0-8160c81610b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'reset_action' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>adefbd30-7bf4-4f0a-9d81-075382f56fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
