<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-tk21u7bohyx3</name>
   <tag></tag>
   <elementGuidId>64828332-1e5b-48be-8ef4-47606d1a22d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-tk21u7bohyx3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-tk21u7bohyx3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>804c4a09-c0ce-4cdb-9fc1-ebc142eeb5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>7a9d5208-281f-4714-b633-0f18d5669a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR&amp;co=aHR0cHM6Ly93d3cuZmJzYnguY29tOjQ0Mw..&amp;hl=en-GB&amp;v=a9s0j4pCVT6gaTEkLiFbtZPH&amp;theme=light&amp;size=normal&amp;cb=e4qbys531z09</value>
      <webElementGuid>45ceba53-90e9-4d33-8f71-e7a79c085939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>4a3db1ae-7530-4a71-941b-7f5796e3f54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>ea47f92c-8626-447b-a9f6-6a0a9007d0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>44d46938-6f0d-4036-b6a7-1abb24ba0849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-tk21u7bohyx3</value>
      <webElementGuid>6b8d028c-9eb7-4abd-a8ec-66c38c2c1da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3036a707-9597-472c-8f0c-e528610dfd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>944d512c-3f2a-4832-94d4-e4f829a7c1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>3a71e5ab-82c4-48c9-bd65-42d819738913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_7t5v chrome webkit win x1 Locale_en_GB&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>5e738df2-ebb0-4f72-8936-9770b49c9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Facebook/iframe_concat(Help us confirm that it, , s _890ae7</value>
      <webElementGuid>6c094934-dfad-4377-8cbd-d1085b18dffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-tk21u7bohyx3']</value>
      <webElementGuid>03cac97c-7551-4d01-b1a8-e459860a820f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>77f03283-4337-4fa8-827a-f929aebbff4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc9qjcUAAAAADTnJq5kJMjN9aD1lxpRLMnCS2TR&amp;co=aHR0cHM6Ly93d3cuZmJzYnguY29tOjQ0Mw..&amp;hl=en-GB&amp;v=a9s0j4pCVT6gaTEkLiFbtZPH&amp;theme=light&amp;size=normal&amp;cb=e4qbys531z09' and @name = 'a-tk21u7bohyx3']</value>
      <webElementGuid>03f1d635-dfb9-4119-a841-aaa1d76878cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
