<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(Help us confirm that it, , s _890ae7</name>
   <tag></tag>
   <elementGuidId>f2f0e986-1bd3-4f57-aa9f-1a02400141ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='captcha-recaptcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#captcha-recaptcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>86c58324-89c7-496d-b9f3-4f3bce919e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captcha-recaptcha</value>
      <webElementGuid>31f71c90-12a5-4c1a-bf5b-f99946f2e2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>241.5104217529297</value>
      <webElementGuid>9e3dddf2-3548-48cb-a6d2-dc394d26319c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js4msrqk ggolc4ur iwso50tu f5m7p0br</value>
      <webElementGuid>2a04532e-9870-49cd-8f95-edb56fac94d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/common/referer_frame.php</value>
      <webElementGuid>0a44f667-829c-4352-8400-9b882ab44a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49f85253-de57-4767-89a0-b5debcd7c7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha-recaptcha&quot;)</value>
      <webElementGuid>907ba388-0463-45f9-b564-a45f17f01c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='captcha-recaptcha']</value>
      <webElementGuid>b8b7c216-d42e-4329-9eaf-822da6df67be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollview']/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/iframe</value>
      <webElementGuid>efd6fb95-7f8e-48fd-af33-2cf45f69c3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6800e423-25bc-44ed-84be-41d565771c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'captcha-recaptcha' and @src = '/common/referer_frame.php']</value>
      <webElementGuid>ba21f6e8-c2a9-427f-bec9-5d9960509bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
