<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter number_phone</name>
   <tag></tag>
   <elementGuidId>3a0e9dce-3da6-4df8-8b38-029098334a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jsc_c_c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jsc_c_c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85950afe-254a-4601-b627-e2bf0586725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>b14c7a87-c350-4d47-a8cc-83a28f84ead5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b7c2001-8e20-455e-bac2-df99a7c43b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>2b9c8f97-f41e-4893-ae9f-a7973139a5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jsc_c_c</value>
      <webElementGuid>15ba5c7a-0aee-48aa-a3e9-ab6cf5985cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c3b3a046-5c0e-490b-80fc-2a725d43f346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>e302d8f9-e6d7-45b8-91c8-229f094815b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qi72231t s3jn8y49 k14qyeqv mz1h5j5e icdlwmnq nu7423ey f5m7p0br iwso50tu ggolc4ur js4msrqk bdao358l pbevjfx6 gxngx1o2 gh55jysx ld7irhx5 n68fow1o r227ecj6 gt60zsk1 o1z8t71x mfclru0v rh5b4hnh najc6n2f</value>
      <webElementGuid>07eacc43-de71-483d-9a11-b8f3927bc971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7dee015-b8b6-49a8-9dca-e338f3d3af47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76c05518-ee6c-4d8d-939a-d9703415196c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsc_c_c&quot;)</value>
      <webElementGuid>5cf3a8a7-bc23-44d1-b4aa-7ddc9c29804f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jsc_c_c']</value>
      <webElementGuid>1c95e624-bfa7-4a30-bf38-62f5e37f086b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollview']/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/label/div/div[2]/input</value>
      <webElementGuid>9fae99ef-8d1f-48d5-843a-94250aadc9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>823b9322-4b30-4981-a5d6-df6caf629461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jsc_c_c' and @name = 'phone' and @type = 'text']</value>
      <webElementGuid>6d059d62-d75f-4442-a2cf-c5212e0bcfa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
