<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To verify your mobile number, please _653879</name>
   <tag></tag>
   <elementGuidId>60243177-cb47-4f25-b265-2fec33a37442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jsc_c_e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jsc_c_e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a4ac503-853d-47af-95e1-345b25ba6106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>5a320350-5075-42b0-ac33-69220f3d59ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d97f2c77-fab0-4e8c-8f50-487995bbc18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>5ff2ecde-df57-4bcb-8aec-00e4e84244c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jsc_c_e</value>
      <webElementGuid>f508530a-c1bf-4462-a1ff-4f845d776c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a17e0cc7-af00-42d3-ba99-6165308fc3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qi72231t s3jn8y49 k14qyeqv mz1h5j5e icdlwmnq nu7423ey f5m7p0br iwso50tu ggolc4ur js4msrqk bdao358l pbevjfx6 gxngx1o2 gh55jysx ld7irhx5 n68fow1o r227ecj6 gt60zsk1 o1z8t71x mfclru0v rh5b4hnh najc6n2f</value>
      <webElementGuid>a0e75cb3-3a2d-44b0-ae96-36eb3701a102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c13f9852-ba89-494c-99f3-ddf0c02e5ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf2a2cc3-1ff7-441d-bd7d-79e9687d1e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7acc0169-e7d9-4ca0-a1ef-3b3fb7ad3b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsc_c_e&quot;)</value>
      <webElementGuid>80a910c1-4aec-4361-9dd9-4d36b84256fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jsc_c_e']</value>
      <webElementGuid>f70d9159-f02e-4620-a861-c1b0b9135489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollview']/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/label/div/div/input</value>
      <webElementGuid>a26afb20-03e6-4983-8ff3-52a76e9e7166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d1550ee0-97fc-4c95-8456-f1dfa7aa869d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jsc_c_e' and @type = 'text']</value>
      <webElementGuid>d809a54e-b13d-4169-be7d-b9e4b05ff4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
