<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To confirm your account, enter the 5-_70a6c3</name>
   <tag></tag>
   <elementGuidId>388d51ce-ed6a-4867-a0bb-e25fc90a14f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jsc_c_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jsc_c_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fb02fa0-2c50-46d6-a7c0-592f0d2c559d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>5304cc72-ec27-4c4e-81d4-bd0170a750d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bce23fe9-0bb5-454c-9f1c-5ea29cbce3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>c72f89a5-85d0-4167-b3ec-a92373f8fa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jsc_c_5</value>
      <webElementGuid>83508126-0abf-4618-beb7-468b62b41f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>97f9572f-e68f-4c2a-b23a-2f4a49606804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qi72231t s3jn8y49 k14qyeqv mz1h5j5e icdlwmnq nu7423ey f5m7p0br iwso50tu ggolc4ur js4msrqk bdao358l pbevjfx6 gxngx1o2 gh55jysx ld7irhx5 n68fow1o r227ecj6 gt60zsk1 o1z8t71x mfclru0v rh5b4hnh najc6n2f</value>
      <webElementGuid>db7b9bff-a2e0-4c90-9f97-3c67275a343b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20355881-4e96-424c-b4b4-77d52a4364a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>885049c3-f53f-4468-8536-1b999b4f3bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsc_c_5&quot;)</value>
      <webElementGuid>9db32cf9-3c5e-4e0c-925b-e7df8bbb86cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jsc_c_5']</value>
      <webElementGuid>69699e93-fe57-4bb9-a37a-3dbaaa92e8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollview']/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/label/div/div/input</value>
      <webElementGuid>c224c1d5-f62f-496a-a006-908af9a2b960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>53ce6e21-21fb-4d2f-82e5-cea67043d821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jsc_c_5' and @type = 'text']</value>
      <webElementGuid>6007a99f-f062-4028-a187-5db0c7ebdf3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
