<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please check your emails for a messag_6d8c97</name>
   <tag></tag>
   <elementGuidId>aaafa490-4a14-4767-bdb8-191be1013df3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recovery_code_entry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recovery_code_entry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1efb0e39-fc32-4f89-af61-a48f39639992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9da53f07-cb93-4dc2-a34c-d1769d28e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w _9o1_</value>
      <webElementGuid>99bc9d34-4294-43b3-a0bd-c31dc0f2906b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>7dd7d9a3-f6fb-4df6-98ba-2e39def354eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recovery_code_entry</value>
      <webElementGuid>caf1b6d9-13ec-4dff-a4e4-a29218902704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>407f06a5-3d1c-4e54-9ae0-9649fb7b06f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>593f50ae-56ab-4ae7-b2c8-0587f6394c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>04ddada1-165b-4ef7-a059-25c53141d9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recovery_code_entry&quot;)</value>
      <webElementGuid>ffa37a9a-212e-48fa-977e-646173cda959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recovery_code_entry']</value>
      <webElementGuid>5f2e063b-8964-4efa-b2ad-3861b7a3eb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_QT']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>e40dce91-da60-4f25-8979-b70f51fbc86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b4f964e3-ebe4-47c6-8ad0-4337ae3d13a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n' and @id = 'recovery_code_entry' and @placeholder = 'Enter code']</value>
      <webElementGuid>2f40ed02-4754-4f40-a3b9-4db2a2beda5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
