<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>ff7b6c44-30da-4280-bbce-760287b30afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='reset_action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;reset_action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a76f2a93-05fc-46d0-8714-ea05dba73539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b73d9bbd-81f3-4a04-8575-c99dc2a710e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy</value>
      <webElementGuid>859c7df7-e24b-4cc1-9310-defdd171b66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reset_action</value>
      <webElementGuid>f9212f89-16c1-40d2-adea-c92dea20a2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ($(&quot;recover_openid&quot;).checked) {OpenIDConnectAuthentication.startAuth(&quot;https:\/\/accounts.google.com\/o\/oauth2\/auth?client_id=15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com&amp;state=ARdfNUJDPpBvEczlepBzQo8cMMlKD9i73wcow-YbwFbyM3rObnmd7ON2J3w74XQb-w4hE0PKCIDmwW8Vr4bMc9PcQMA9fnZAagGW5-WminOdyZqc07LJxgwRj51dMN4XRpjZSWf1xleVLYRP7qqezyJXvZq99VvLDRonZzxM5fgogSJXhvuRNfMYM0UQ-2YU0cjdzlMJ5awib7A_Kyxh4ph6-9sXBF1jQR3Zo9W7ffYnCkFmiDly70ZZom__RKPTVKEjBThYpP0wgvk05U_eWfkj&amp;response_type=code&amp;redirect_uri=https\u00253A\u00252F\u00252Fwww.facebook.com\u00252Foauth2\u00252Fredirect\u00252F&amp;scope=openid+email&amp;login_hint=fchaerin.c196\u002540gmail.com&quot;, &quot;account_recovery&quot;)}</value>
      <webElementGuid>a47239cc-8484-4205-9d02-b56719ac70be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b2bf64e6-f511-4c83-bfca-11e801a1d97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>f072237b-ba37-471d-b395-fec3dd085173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initiate_interstitial&quot;)/div[@class=&quot;uiInterstitialBar uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;rfloat _ohf&quot;]/button[@class=&quot;_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy&quot;]</value>
      <webElementGuid>50d0d997-31bf-4030-8482-d86e07473c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='reset_action']</value>
      <webElementGuid>2f5ff727-82e6-4c20-a1ff-9ad239d7a982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initiate_interstitial']/div[3]/div/div/button</value>
      <webElementGuid>0107c4e3-6f5a-4cf6-8946-dbb7eb12121f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not you?'])[1]/following::button[1]</value>
      <webElementGuid>a36b8ffd-9f82-4b59-9269-771bd1779d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook user'])[1]/following::button[1]</value>
      <webElementGuid>a21472b5-28c3-4618-b165-53232016a5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No longer have access to these?'])[1]/preceding::button[1]</value>
      <webElementGuid>f7c13e90-8c45-4b2e-a3b7-bc3e0d716dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::button[1]</value>
      <webElementGuid>cb6422ce-fbee-4308-af81-607679fa3984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>98c98efc-aac4-4b65-9d51-384149ce7f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>93625889-db3c-4999-9a17-d4bef649503c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'reset_action' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>94231c06-c5f6-4c84-b9b2-638d70215662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
