<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apiuserspage2</name>
   <tag></tag>
   <elementGuidId>112e3299-40b9-4c0c-85bc-aee4e777b415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a814e11e-a503-40d6-8d40-71680e3d8cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>3b304ec9-2c9b-463f-a711-f4d1c2b1012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>d7523e85-7687-47f6-b850-b105439208a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/api/users?page=2</value>
      <webElementGuid>ee90c7ba-5636-4fa5-b7ac-9bdea8338adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;output&quot;]/div[@class=&quot;request&quot;]/p[@class=&quot;request-title&quot;]/strong[1]/a[@class=&quot;link try-link&quot;]/span[@class=&quot;url&quot;]</value>
      <webElementGuid>715a4a3d-04ef-4f06-abd6-2e86568a2ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      <webElementGuid>a5e82516-60a8-42f1-b5cf-ec716d3e1625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed response'])[1]/following::span[1]</value>
      <webElementGuid>64e3edec-74fe-4e56-b5b1-9cf46031b4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://reqres.in/#support-heading'])[1]/preceding::span[2]</value>
      <webElementGuid>5a854b1b-1575-4f8e-bc21-63b51790d499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/api/users?page=2']/parent::*</value>
      <webElementGuid>017fd307-230c-4823-bc6f-aa52527b84c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>0a312f6f-2ba6-4907-9f2d-d8e53df411b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '/api/users?page=2' or . = '/api/users?page=2')]</value>
      <webElementGuid>a63f86c8-5c32-459b-a025-49a659c12469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
