<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create New Account</name>
   <tag></tag>
   <elementGuidId>0d183ff7-0123-4bd1-9558-5f10bd8d16e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='u_0_0_U7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_0_U7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cc69d57-dc87-432a-86b1-0683cf3f5915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37afa63d-753a-4ca4-8816-65d9d832641e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _6lti _4jy6 _4jy2 selected _51sy</value>
      <webElementGuid>06334853-86d2-4c99-b834-e028bdc957f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dda5b8c5-f3d3-49ff-abb0-a3cf3188b59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ajaxify</name>
      <type>Main</type>
      <value>/reg/spotlight/</value>
      <webElementGuid>cd8697a3-c4bc-47c5-ac4d-ee065a4ac5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_0_U7</value>
      <webElementGuid>314f1910-6e82-4e04-99a9-129cd1abff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>open-registration-form-button</value>
      <webElementGuid>f6c431c8-ad74-4219-b67e-327ddd87e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>95226134-a1e2-4632-bf0a-f9b877fe06da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Account</value>
      <webElementGuid>e0190cab-2d84-44b7-bc87-182bceb1b731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_0_U7&quot;)</value>
      <webElementGuid>58668e16-0c51-477c-8db0-e85a2fafe225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>679ad092-df51-4f0e-8612-a0373992b72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43f048a3-1de1-44e0-862d-1cc87dd6cf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _6lti _4jy6 _4jy2 selected _51sy</value>
      <webElementGuid>ee7e7855-174f-4d2e-9af0-747ee119451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>395da9b6-577c-4f21-a575-e43111d97eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ajaxify</name>
      <type>Main</type>
      <value>/reg/spotlight/</value>
      <webElementGuid>916e9a4e-908a-4001-8c5d-799c95436e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_0_2n</value>
      <webElementGuid>cc3b20a5-ea96-4861-b08e-b1f41fae1913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>open-registration-form-button</value>
      <webElementGuid>346a6078-7a61-4b86-9d81-1badad12e68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>31037ef2-005f-4f35-9052-ad6da303ad0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Account</value>
      <webElementGuid>7c91a514-51c9-45d2-a4d1-70586f4f65c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_0_2n&quot;)</value>
      <webElementGuid>8af89be4-7492-44ef-adf9-b03db37cd3a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_0_U7']</value>
      <webElementGuid>d925d70a-5cc1-4d76-b1e9-2b3cd752dcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_IH']/div[5]/a</value>
      <webElementGuid>24bedf9f-d5c1-402f-8913-68b9c3b19d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create New Account')]</value>
      <webElementGuid>50587707-f7a9-4e21-8265-1e18bf3a3969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/following::a[1]</value>
      <webElementGuid>fe32d108-ec11-4bd4-b5bf-5c4b8fe5d7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[2]</value>
      <webElementGuid>df13c29c-393d-4997-afe7-139e774c6a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Page'])[1]/preceding::a[1]</value>
      <webElementGuid>9596f1e4-34bc-4adf-a25a-da3e8728a3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New Account']/parent::*</value>
      <webElementGuid>772ac4eb-9af1-47ed-bc66-f3a7f8152a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>ac08ab82-3538-433e-8d5e-b8d2be527196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>f6e1c00a-fe46-4f83-b51e-bd65205ec42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_0_0_U7' and (text() = 'Create New Account' or . = 'Create New Account')]</value>
      <webElementGuid>a7e83a5c-5efc-4419-baf1-8eb2e1127658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_0_2n']</value>
      <webElementGuid>710b6c4f-f456-42b4-ba06-dd854899b589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_x+']/div[5]/a</value>
      <webElementGuid>2034c91a-d049-4914-a781-46cdcd118985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_0_0_2n' and (text() = 'Create New Account' or . = 'Create New Account')]</value>
      <webElementGuid>46b1561e-334c-46c5-8541-d7e431f76ef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
